-- Create subscriptions table for recurring client subscriptions
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint REFERENCES public.companies(id) ON DELETE CASCADE,
  contact_id bigint REFERENCES public.contacts(id) ON DELETE SET NULL,
  subscription_type text NOT NULL, -- 'Control4 4Sight', 'Re:Sure', '2n Intercom', 'Security', 'Fire'
  title text NOT NULL,
  amount numeric(10,2) DEFAULT 0.00,
  billing_frequency text DEFAULT 'Annual', -- 'Annual', 'Bi-Annual', 'Quarterly', 'Monthly'
  renewal_date date NOT NULL,
  status text DEFAULT 'Active', -- 'Active', 'Pending Renewal', 'Renewed', 'Cancelled'
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users full access
CREATE POLICY "Allow full access to subscriptions" ON public.subscriptions
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
