-- Create junction table for M:N Contact <-> Company relationship
CREATE TABLE IF NOT EXISTS public.contact_companies (
    id bigint generated by default as identity PRIMARY KEY,
    contact_id bigint NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
    company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    role text, -- e.g. "Board Member", "consultant"
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(contact_id, company_id) -- Prevent duplicate links
);

-- Enable RLS
ALTER TABLE public.contact_companies ENABLE ROW LEVEL SECURITY;

-- Policies (consistent with other tables)
CREATE POLICY "Enable read for authenticated" ON public.contact_companies FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated" ON public.contact_companies FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated" ON public.contact_companies FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated" ON public.contact_companies FOR DELETE TO authenticated USING (true);

-- Backfill: Insert existing primary companies into the junction table
INSERT INTO public.contact_companies (contact_id, company_id, role)
SELECT id, company_id, 'Primary'
FROM public.contacts
WHERE company_id IS NOT NULL
ON CONFLICT (contact_id, company_id) DO NOTHING;

-- Trigger: Whenever a contact's primary company_id is set/changed, ensure it exists in contact_companies
CREATE OR REPLACE FUNCTION public.sync_contact_primary_company()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.company_id IS NOT NULL THEN
        INSERT INTO public.contact_companies (contact_id, company_id, role)
        VALUES (NEW.id, NEW.company_id, 'Primary')
        ON CONFLICT (contact_id, company_id) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_contact_primary_change ON public.contacts;
CREATE TRIGGER on_contact_primary_change
    AFTER INSERT OR UPDATE OF company_id ON public.contacts
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_contact_primary_company();

-- Register resource is done in frontend code (App.tsx / CRM.tsx)
