
-- Adapted to match existing schema (using bigint instead of uuid for keys)
CREATE TABLE contracts (
  id bigint generated by default as identity PRIMARY KEY,
  company_id bigint REFERENCES companies(id),
  contract_name text NOT NULL,
  expiry_date date NOT NULL,
  status text DEFAULT 'active'
);

ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;

-- Simple policy for now as requested
CREATE POLICY "All access" ON contracts FOR ALL TO authenticated USING (true);
